# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
print("NumPy Version:", np.__version__)

# Print the NumPy configuration
print("\nNumPy Configuration:")
print(np.__config__.show())

NumPy Version: 1.26.0

NumPy Configuration:
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "14.0.0",
      "commands": "clang"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.2",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "14.0.0",
      "commands": "clang++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "openblas64",
      "found": true,
      "version": "0.3.23.dev",
      "detection method": "pkgconfig",
      "include directory": "/usr/local/include",
      "lib directory": "/usr/local/lib",
      "openblas configuration": "USE_64BITIN

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/__config__.py:149: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
a = np.random.rand(2, 3, 5)


### 4. Print a.


In [4]:
print(a)

[[[0.17859731 0.32067963 0.27923529 0.82740732 0.28444771]
  [0.12533796 0.242349   0.11936861 0.12966771 0.1829265 ]
  [0.62507205 0.04361212 0.18663396 0.12345446 0.67041062]]

 [[0.8882127  0.47722856 0.52342262 0.53714614 0.20483356]
  [0.9574217  0.94169856 0.66111027 0.47744334 0.29307712]
  [0.19904885 0.1074272  0.58491449 0.95164437 0.09983978]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [5]:
import numpy as np

# Create a 5x2x3 array filled with 1s
b = np.ones((5, 2, 3))


### 6. Print b.


In [6]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [7]:
a = [1, 2, 3]
b = [4, 5, 6]

# Check if they have the same length
if len(a) == len(b):
    print("a and b have the same size.")
else:
    print("a and b do not have the same size.")


a and b have the same size.



### 8. Are you able to add a and b? Why or why not?


In [8]:
a = np.random.rand(2,3,5)
b = np.ones((5,2,3))
can_add=a.shape==b.shape
print("Can a and b addes?",can_add)
print("No because a and b don't have the same shape")

Can a and b addes? False
No because a and b don't have the same shape




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [9]:
import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array b (let's assume b needs reshaping and transposition)
b = np.random.rand(30)  # A flat array with 30 elements (can be reshaped into 2x3x5)

# Reshape b into a 2x3x5 array
c = b.reshape(2, 3, 5)

# If you need to transpose the array (for example, swapping axes), you can do:
c = np.transpose(c, (0, 2, 1))  # This swaps axis 1 and axis 2 (i.e., transposing)

print("Array a shape:", a.shape)
print("Array c shape:", c.shape)



Array a shape: (2, 3, 5)
Array c shape: (2, 5, 3)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [10]:
import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array c (reshaped version of b, with shape 2x3x5)
b = np.random.rand(30)  # A flat array with 30 elements (can be reshaped into 2x3x5)
c = b.reshape(2, 3, 5)

# Add a and c
d = a + c

print("Shape of a:", a.shape)
print("Shape of c:", c.shape)
print("Shape of d:", d.shape)


Shape of a: (2, 3, 5)
Shape of c: (2, 3, 5)
Shape of d: (2, 3, 5)



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [11]:
import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array b and reshape it to create array c with shape (2, 3, 5)
b = np.random.rand(30)  # A flat array with 30 elements
c = b.reshape(2, 3, 5)

# Add a and c to create d
d = a + c

# Print a and d to observe the difference
print("Array a:")
print(a)
print("\nArray d (a + c):")
print(d)




Array a:
[[[0.6425073  0.15226252 0.114399   0.52849202 0.1779881 ]
  [0.67158984 0.0333585  0.8334329  0.4124452  0.93019325]
  [0.16305388 0.87684794 0.84704566 0.85156739 0.15554908]]

 [[0.73090798 0.93958703 0.57926517 0.40292599 0.26484431]
  [0.30485157 0.16464277 0.48641771 0.10740976 0.17761926]
  [0.95739644 0.86336956 0.89418814 0.08121732 0.92417244]]]

Array d (a + c):
[[[1.49256144 0.4481022  1.05631698 0.64490907 1.15477419]
  [1.328329   0.74326542 1.76997539 1.23132525 1.39643666]
  [0.35739186 1.04486528 0.89632871 1.5846345  0.23971819]]

 [[1.10834792 1.60487219 1.18249993 1.13960099 1.07307673]
  [0.77110444 0.55944568 0.56907849 0.72569853 0.8438693 ]
  [1.7736534  1.24089552 0.98957622 1.07386686 1.01288384]]]



### 12. Multiply a and c. Assign the result to e.


In [12]:
import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array b and reshape it to create array c with shape (2, 3, 5)
b = np.random.rand(30)  # A flat array with 30 elements
c = b.reshape(2, 3, 5)

# Multiply a and c to create e
e = a * c

# Print a, c, and e to observe the results
print("Array a:")
print(a)
print("\nArray c:")
print(c)
print("\nArray e (a * c):")
print(e)


Array a:
[[[0.63616976 0.83208023 0.91136972 0.29737835 0.16739698]
  [0.64208889 0.13749646 0.42142791 0.85154832 0.18371668]
  [0.58796664 0.86475549 0.44617628 0.37515616 0.70494747]]

 [[0.06224099 0.25641337 0.39296272 0.25592025 0.83884617]
  [0.97877843 0.88833761 0.1434054  0.18165921 0.03314164]
  [0.9034667  0.68626392 0.82787877 0.37518894 0.97883533]]]

Array c:
[[[0.76176036 0.46356463 0.90398674 0.83113514 0.4695375 ]
  [0.71896036 0.07557183 0.95039102 0.65508128 0.72162836]
  [0.82804526 0.61437441 0.75457568 0.69570294 0.55996477]]

 [[0.08139594 0.29592173 0.03581912 0.45589463 0.19731845]
  [0.02606572 0.55180339 0.57575887 0.56774457 0.38507561]
  [0.48917503 0.30005247 0.19401724 0.96526048 0.05436049]]]

Array e (a * c):
[[[0.4846089  0.38572296 0.82386614 0.24716159 0.07859916]
  [0.46163645 0.01039086 0.4005213  0.55783337 0.13257517]
  [0.48686299 0.53128364 0.33667377 0.26099724 0.39474575]]

 [[0.00506616 0.07587829 0.01407558 0.11667267 0.16551983]
  [0.0255



### 13. Does e equal to a? Why or why not?


In [13]:
import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array b and reshape it to create array c with shape (2, 3, 5)
b = np.random.rand(30)  # A flat array with 30 elements
c = b.reshape(2, 3, 5)

# Multiply a and c to create e
e = a * c

# Check if e is equal to a
print("Does e equal a?", np.array_equal(a, e))


Does e equal a? False




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [14]:
#import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array b and reshape it to create array c with shape (2, 3, 5)
b = np.random.rand(30)  # A flat array with 30 elements
c = b.reshape(2, 3, 5)

# Add a and c to create d
d = a + c

# Identify the max, min, and mean values in d
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

# Print the results
print("Max value in d:", d_max)
print("Min value in d:", d_min)
print("Mean value in d:", d_mean)


Max value in d: 1.6549220859145017
Min value in d: 0.2215157027778193
Mean value in d: 0.8836448524733822



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [15]:
import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array b and reshape it to create array c with shape (2, 3, 5)
b = np.random.rand(30)  # A flat array with 30 elements
c = b.reshape(2, 3, 5)

# Add a and c to create d
d = a + c

# Create an empty array f with the same shape as d (2x3x5)
f = np.empty_like(d)

# Print the shape of f to verify
print("Shape of f:", f.shape)

Shape of f: (2, 3, 5)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [16]:
import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array b and reshape it to create array c with shape (2, 3, 5)
b = np.random.rand(30)  # A flat array with 30 elements
c = b.reshape(2, 3, 5)

# Add a and c to create d
d = a + c

# Identify the max, min, and mean values in d
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

# Create an empty array f with the same shape as d (2x3x5)
f = np.empty_like(d)

# Loop through the elements in d and populate f according to the rules
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75

# Print the populated array f
print("Array f:")
print(f)


Array f:
[[[ 25.  25.  75.  75.  75.]
  [100.  25.  25.  25.  75.]
  [  0.  75.  25.  25.  75.]]

 [[ 75.  75.  75.  25.  25.]
  [ 75.  25.  25.  25.  75.]
  [ 25.  75.  25.  75.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [17]:
import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array b and reshape it to create array c with shape (2, 3, 5)
b = np.random.rand(30)  # A flat array with 30 elements
c = b.reshape(2, 3, 5)

# Add a and c to create d
d = a + c

# Identify the max, min, and mean values in d
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

# Create an empty array f with the same shape as d (2x3x5)
f = np.empty_like(d)

# Loop through the elements in d and populate f according to the rules
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75

# Print d and f to compare the results
print("Array d:")
print(d)

print("\nArray f:")
print(f)


Array d:
[[[1.21780474 1.36509483 1.26735796 1.12182521 0.86438415]
  [1.35480616 0.61956401 1.35887834 1.42329238 0.83507205]
  [0.98814862 0.35993176 1.10906055 0.67235728 1.61254943]]

 [[1.51676587 0.93204819 0.4988603  0.95291459 0.48334884]
  [1.36672769 1.69531575 1.7231275  1.44179472 1.39908476]
  [0.35266242 1.24738848 0.70093034 0.53285567 1.65593361]]]

Array f:
[[[ 75.  75.  75.  75.  25.]
  [ 75.  25.  75.  75.  25.]
  [ 25.  25.  75.  25.  75.]]

 [[ 75.  25.  25.  25.  25.]
  [ 75.  75. 100.  75.  75.]
  [  0.  75.  25.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [18]:
import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array b and reshape it to create array c with shape (2, 3, 5)
b = np.random.rand(30)  # A flat array with 30 elements
c = b.reshape(2, 3, 5)

# Add a and c to create d
d = a + c

# Identify the max, min, and mean values in d
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

# Create an empty array f with the same shape as d (2x3x5), but with string data type
f = np.empty_like(d, dtype=object)  # Use dtype=object to store strings

# Loop through the elements in d and populate f according to the rules
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_max:
                f[i, j, k] = "E"
            elif d[i, j, k] == d_min:
                f[i, j, k] = "A"
            elif d[i, j, k] == d_mean:
                f[i, j, k] = "C"
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = "B"
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = "D"

# Print the populated array f
print("Array f with string labels:")
print(f)


Array f with string labels:
[[['D' 'B' 'D' 'E' 'B']
  ['D' 'D' 'D' 'D' 'B']
  ['B' 'D' 'D' 'B' 'B']]

 [['A' 'D' 'B' 'B' 'B']
  ['B' 'D' 'D' 'D' 'D']
  ['D' 'B' 'B' 'B' 'B']]]
